# PID gains for the steer_bot_hardware_gazebo plugin.

gains:
    rear_right_wheel_joint:
        p: 6.0 # Ku = 10, Tu = 0.385
        i: 3.00
        d: 0.3
        i_clamp: 10.0
    rear_left_wheel_joint:
        p: 6.0
        i: 3.00
        d: 0.3
        i_clamp: 10.0

